name: run unit tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Get go dependencies
        run: go get -v -t -d ./...
      - name: Run tests
        run: go test -timeout 30s ./...
      - name: Test build
        run: go build -v .